TMF/Controllers/FindController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TMF.Models.Context;
using TMF.Models.Entity;

namespace TMF.Controllers
{
    public class FindController : Controller
    {
        TmfContext db = new TmfContext();
        public ActionResult Index()
        {
            List<lobbys> liste = new List<lobbys>();
            if (Session["id"]!=null)
            {
                int id=int.Parse(Session["id"].ToString());
                liste = (from lobby in db.lobby
                         where lobby.userAl.id == id && lobby.status == 0
                         select (lobby)).ToList<lobbys>();
            }
            return View(liste);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(FormCollection fc)
        {
            return View();
        }

        public ActionResult Search()
        {
            var abc = db.user.Find(11);
            
            return View();
        }

        [HttpPost]
        public ActionResult Search(FormCollection fc)
        {
           
            List<users> liste = new List<users>();
            List<userGameDescs> query = (from userGameDesc in db.userGameDesc
                         select (userGameDesc)).ToList();

            int min = int.Parse(fc["minDataCS"]); //slider min değer
            int max = int.Parse(fc["maxDataCS"]); //max değer

            int minRank = 86 + (2 * min - 1);
            int maxRank = 86 + (2 * max);
            if (min==10)
            {
                minRank -= 1;
            }
            if (max == 10)
            {
                maxRank -= 2;
            }
            List<userGameDescs> query1 = query.Where(e => e.compAtt.id >= minRank).Where(e => e.compAtt.id <= maxRank).ToList<userGameDescs>();
            query.Clear();
            foreach (var item2 in query1)
            {
                foreach (var item in item2.userGame.userGameDesc)
	                {
                        query.Add(item);
	                } 
              
               
            }

            List<userGameDescs> q1 = new List<userGameDescs>();
            List<userGameDescs> q2 = new List<userGameDescs>();
            List<userGameDescs> q3 = new List<userGameDescs>();
            List<userGameDescs> q4 = new List<userGameDescs>();
            List<userGameDescs> q5 = new List<userGameDescs>();
            List<userGameDescs> q6 = new List<userGameDescs>();



            string AWP = fc["AWP"];
            if (AWP == "on")
            {
                q1 = query.Where(e => e.compAtt.value == "AWP").ToList();
            }
            
            string Lurker = fc["Lurker"];
            if (Lurker == "on")
            {
                q2 = query.Where(e => e.compAtt.value == "Lurker").ToList();
            }
            
            string Rifler = fc["Rifler"];
            if (Rifler == "on")
            {
                q3 = query.Where(e => e.compAtt.value == "Rifler").ToList();
            }

            string IGL = fc["IGL"];
            if (IGL == "on")
            {
                q4 = query.Where(e => e.compAtt.value == "IGL").ToList();
            }

            string Supporter = fc["Supporter"];
            if (Supporter == "on")
            {
                q5 = query.Where(e => e.compAtt.value == "Supporter").ToList();
            }

            string Fragger = fc["Fragger"];
            if (Fragger == "on")
            {
                q6 = query.Where(e => e.compAtt.value == "Fragger").ToList();
            }

            if (AWP == null && Lurker == null && Rifler == null && IGL == null && Supporter == null && Fragger == null)
            {
               
                var query2 = query.GroupBy(e => e.userGame.user.id).ToList();
                string yas = fc["yas"];
                int minHours = int.Parse(fc["minHours"]);
                int maxHours = int.Parse(fc["maxHours"]);

                foreach (var item in query2)
                {
                    if (Session["id"]!=null)
                    {
                        if (item.Key == int.Parse(Session["id"].ToString()))
                        {
                            continue;
                        }
                    }
                    
                    users u = db.user.Find(item.Key);
                    string Mic = fc["Mic"];
                    if (Mic == "on")
                    {
                        if (u.mic == false)
                        {
                            continue;
                        }
                    }
                    string Headset = fc["Headset"];
                    if (Headset == "on")
                    {
                        if (u.headset == false)
                        {
                            continue;
                        }
                    }
                    if (yas == "-16")
                    {
                        if (DateTime.Now.Year - u.dateOfBirth.Year < 16)
                        {
                            if (minHours == 0 && maxHours == 0)
                            {
                                liste.Add(u);
                            }
                            else if (u.userGame.Find(e => e.game.id == 2).time > minHours && maxHours == 0)
                            {
                                liste.Add(u);
                            }
                            else if (minHours == 0 && u.userGame.Find(e => e.game.id == 2).time < maxHours)
                            {
                                liste.Add(u);
                            }
                            else if (u.userGame.Find(e => e.game.id == 2).time > minHours && u.userGame.Find(e => e.game.id == 2).time < maxHours)
                            {
                                liste.Add(u);
                            }

                        }

                    }
                    else if (yas == "+16")
                    {
                        if (DateTime.Now.Year - u.dateOfBirth.Year > 16)
                        {
                            if (minHours == 0 && maxHours == 0)
                            {
                                liste.Add(u);
                            }
                            else if (u.userGame.Find(e => e.game.id == 2).time > minHours && maxHours == 0)
                            {
                                liste.Add(u);
                            }
                            else if (minHours == 0 && u.userGame.Find(e => e.game.id == 2).time < maxHours)
                            {
                                liste.Add(u);
                            }
                            else if (u.userGame.Find(e => e.game.id == 2).time > minHours && u.userGame.Find(e => e.game.id == 2).time < maxHours)
                            {
                                liste.Add(u);
                            }
                        }

                    }
                    else
                    {
                        if (minHours == 0 && maxHours == 0)
                        {
                            liste.Add(u);
                        }
                        else if (u.userGame.Find(e => e.game.id == 2).time > minHours && maxHours == 0)
                        {
                            liste.Add(u);
                        }
                        else if (minHours == 0 && u.userGame.Find(e => e.game.id == 2).time < maxHours)
                        {
                            liste.Add(u);
                        }
                        else if (u.userGame.Find(e => e.game.id == 2).time > minHours && u.userGame.Find(e => e.game.id == 2).time < maxHours)
                        {
                            liste.Add(u);
                        }
                    }

                }
            }
            else
            {
                var q = q1.Union(q2).Union(q3).Union(q4).Union(q5).Union(q6).ToList();
                var query2 = q.GroupBy(e => e.userGame.user.id).ToList();
                string yas = fc["yas"];
                int minHours = int.Parse(fc["minHours"]);
                int maxHours = int.Parse(fc["maxHours"]);
                foreach (var item in query2)
                {
                    if (Session["id"] != null)
                    {
                        if (item.Key == int.Parse(Session["id"].ToString()))
                        {
                            continue;
                        }
                    }
                    users u = db.user.Find(item.Key);
                    string Mic = fc["Mic"];
                    if (Mic == "on")
                    {
                        if (u.mic == false)
                        {
                            continue;
                        }
                    }
                    string Headset = fc["Headset"];
                    if (Headset == "on")
                    {
                        if (u.headset == false)
                        {
                            continue;
                        }
                    }
                    if (yas == "-16")
                    {
                        if (DateTime.Now.Year - u.dateOfBirth.Year < 16)
                        {
                            if (minHours == 0 && maxHours == 0)
                            {
                                liste.Add(u);
                            }
                            else if (u.userGame.Find(e => e.game.id == 2).time > minHours && maxHours == 0)
                            {
                                liste.Add(u);
                            }
                            else if (minHours == 0 && u.userGame.Find(e => e.game.id == 2).time < maxHours)
                            {
                                liste.Add(u);

TMF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
    <script src="~/Scripts/js/bootstrap-select.js"></script>
    <script src="~/Scripts/js/layout.js"></script>

</head>
<body>
    <link href="~/Content/css/layout.css" rel="stylesheet" />

    <nav class="navbar navbar-expand-lg navbar-light " style="background-color:rgb(193, 193, 193)!important" padding>
        <div class="navbar-header">
            <a class="navbar-brand" href="@Url.Action("Index","Find")">Team Mate Find</a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <button id="game_btn" type="button" class="btn btn-outline-primary dropdown-toggle " data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Games
                    </button>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" id="1" name="game">League of Legends</a>
                        <a class="dropdown-item" id="2" name="game">CS:GO</a>
                        <span class="dropdown-item disabled" href="#">Rocket League</span>
                        <span class="dropdown-item disabled" href="#">PUBG</span>
                        <span class="dropdown-item disabled" href="#">Fortnite</span>
                    </div>
                </li>

                <li class="nav-item" style="margin-left:180px">
                    <a class="nav-link" href="@Url.Action("Index", "Find")">Home </a>
                </li>
                @if (Session["id"] != null)
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Listeler", "Find")"> Invite Lobbies </a>
                    </li>
                }

                @if (Session["id"] != null && Session["yetki"].ToString() == "1")
                {
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "users")">User List</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Create", "users")">User Create</a>
                    </li>
                }
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Search", "Find")">Cs Search</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("SearchLol", "Find")">Lol Search</a>
                </li>

            </ul>

            <ul class="nav-item navbar-nav navbar-right">

                @if (Session["id"] != null)
                {
                    <li class="btn btn-outline-primary my-2 my-md-0"><span class="fas fa-user"></span> @Html.ActionLink("Profile", "Details/"+Session["id"], "users")</li>
                    <li class="btn btn-outline-danger my-2 mr-2 my-sm-0 ">@Html.ActionLink("Log Out", "LogOut", "users")</li>
                }
                else
                {
                    <li class="btn btn-outline-primary my-2 mr-2 my-sm-0 ">@Html.ActionLink("Login", "Login", "users")</li>
                    <li class="btn btn-outline-primary my-2 my-md-0"><span class="fas fa-user"></span> @Html.ActionLink("Sign Up", "Create", "users")</li>

                }

            </ul>
        </div>
    </nav>

    <div class="container body-content " style="background-color:rgb(193, 193, 193)!important">

        @RenderBody()
        <hr />
    </div>

    @RenderSection("scripts", required: false)

</body>
</html>