TMF/Models/Entity/users.cs
using System;
using System.Collections.Generic;

namespace TMF.Models.Entity
{
    public partial class users
    {
        
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public DateTime dateOfBirth { get; set; }
        public byte[] image { get; set; }
        public bool mic { get; set; }
        public bool headset { get; set; }
        public bool online { get; set; }
        public bool search { get; set; }
        public virtual List<filters> filter { get; set; }
        public virtual List<userGames> userGame { get; set; }
        public virtual roles role { get; set; }
    }
}

TMF/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using TMF.Models.Context;
using TMF.Models.Entity;

namespace TMF.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        private TmfContext db = new TmfContext();
        public ActionResult Index()
        {
            if (Session["yetki"] != null && (Session["yetki"].ToString() == "1" || Session["yetki"].ToString() == "2" || Session["yetki"].ToString() == "3"))
            {
                var users = db.user.Include(u => u.role);
                return View(users.ToList());
            }
            return RedirectToAction("Login");
        }

        public ActionResult Login()
        {

            return View();
        }

        [HttpPost]
        public ActionResult Login(users user)
        {

            if (ModelState.IsValid)
            {
                var usr = db.user.Where(u => u.username == user.username && u.password == user.password).FirstOrDefault();

                if (usr != null)
                {
                    Session["id"] = usr.id;
                    Session["username"] = usr.username;
                    var yetki = (from u in db.user
                                 where u.role.id==usr.role.id
                                 select u.role.name).FirstOrDefault();
                    Session["yetki"] = yetki;
                    return RedirectToAction("Home");
                }
                else
                {
                    ModelState.AddModelError("", "Kullanıcı adı veya şifre hatalı.");
                }        
            }
            return View();
        }

        public ActionResult LogOut()
        {
            Session.Clear();
            return RedirectToAction("Login");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TMF/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using TMF.Models.Context;
using TMF.Models.Entity;
using Newtonsoft.Json;
using TMF.Models.Games.Steam;

namespace TMF.Controllers
{
    public class usersController : Controller
    {
        private TmfContext db = new TmfContext();

        // GET: users
        public ActionResult Index()
        {

            if (Session["id"] != null && Session["yetki"].ToString() == "1")
            {
                var a = db.user.ToList();
                return View(a);
            }
            return RedirectToAction("Login");
        }

        public ActionResult Login()
        {
            if (Session["yetki"] == null)
            {
                return View();
            }
            return RedirectToAction("Index", "Find");
        }


        [HttpPost]
        public ActionResult Login(FormCollection fc)
        {

            var a = fc["usernameL"].ToString();
            var b = fc["passL"].ToString();
            var usr = db.user.Where(u => u.username == a && u.password == b).FirstOrDefault();

            if (usr != null)
            {
                Session["id"] = usr.id;
                Session["Ad"] = usr.username;
                Session["yetki"] = usr.role.id;
                Session["search"] = usr.search == true ? "1" : "0";
                usr.online = true;
                db.Entry(usr).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Find");
            }
            else
            {
                ModelState.AddModelError("", "my db Kullanıcı adı veya şifre hatalı.");
            }


            return View();
        }
        public ActionResult LogOut()
        {
            if (Session["id"] != null)
            {
                var usr = db.user.Find(Session["id"]);
                usr.online = false;
                db.Entry(usr).State = EntityState.Modified;
                db.SaveChanges();
                Session.Clear();
                return RedirectToAction("Index", "Find");
            }
            return RedirectToAction("Index", "Find");

        }

        // GET: users/Details/5
        public ActionResult Details(int? id)
        {
            if (Session["yetki"] != null)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                users users = db.user.Find(id);
                if (users == null)
                {
                    return HttpNotFound();
                }
                return View(users);
            }
            return RedirectToAction("Login");

        }
        [HttpPost]
        public JsonResult getSteamDatas(string connectID)
        {
            if (connectID != "")
            {
                try
                {
                    string url = " http://api.steampowered.com/IPlayerService/GetOwnedGames/v0001/?key=0A6275C1D7258B89774826D89329EE09&steamid=" + connectID + "&include_appinfo=1&format=json ";
                    WebRequest istek = HttpWebRequest.Create(url);
                    WebResponse cevap;
                    cevap = istek.GetResponse();
                    using (StreamReader r = new StreamReader(cevap.GetResponseStream()))
                    {
                        string json = r.ReadToEnd();
                        data item = JsonConvert.DeserializeObject<data>(json);
                        return Json(item, JsonRequestBehavior.AllowGet);
                    }

                }
                catch (Exception)
                {

                    return Json(false);
                }

            }
            return Json(false);

        }

        public JsonResult usernameControl(string username)
        {
            if (username != "" && db.user.Any(u => u.username == username)) //Kullanıcı adı mevcut,kullanılamaz
            {
                return Json("0");

            }
            else if (username != "" && db.user.Any(u => u.username == username) == false) // Kullanıcı adı kullanılabilir
            {
                return Json("1");

            }
            return Json("2");

        }

        // GET: users/Create
        public ActionResult Create()
        {
            ViewBag.gameList = new SelectList(db.game, "id", "name");
            ViewBag.csRanks = new SelectList(db.compAtt.Where(a => a.id <= 104 && a.id > 86), "id", "value");
            ViewBag.lolRanks = new SelectList(db.compAtt.Where(a => a.id <= 81 && a.id > 54), "id", "value");
            return View();
        }

        // POST: users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(FormCollection fc)
        {
            //if (fc["registerPage"] == "1")
            //{
            //    if (((fc["usernameK"]).ToString()).Count() > 4)
            //    {
            //        var a = fc["usernameK"];
            //        var b = fc["passK"];
            //        var c = fc["emailK"];
            //        DateTime dt = new DateTime(2000, 01, 01);
            //        users user = new users();
            //        user.username = a;
            //        user.password = b;
            //        user.dateOfBirth = dt;
            //        user.role = db.role.Where(u => u.id == 3).FirstOrDefault();
            //        db.user.Add(user);
            //        db.SaveChanges();
            //        return RedirectToAction("Login");
            //    }

            //}
            //else
            //{
            //user table data
            string usrname = fc["username"];
            string psw = fc["password"];
            var date1 = fc["date"];
            bool mic = fc["mic"] == "on" ? true : false;
            bool hs = fc["headset"] == "on" ? true : false;

            //userGame table data
            bool lol = fc["League"] == "on" ? true : false;
            bool cs = fc["Counter"] == "on" ? true : false;
            bool pubg = fc["PlayerUnknown's"] == "on" ? true : false;
            bool rocket = fc["Rocket"] == "on" ? true : false;
            bool fort = fc["Fortnite"] == "on" ? true : false;
            int lolHours = int.Parse(fc["lolHours"]);
            int csHours = int.Parse(fc["csHours"]);

            //userGameDesc table data
            var rankcs = fc["rankCs"];
            var ranklol = fc["rankLol"];
            bool awp = fc["AWP"] == "on" ? true : false; //CS ROLES
            bool lurker = fc["Lurker"] == "on" ? true : false;
            bool rifle = fc["Rifler"] == "on" ? true : false;
            bool igl = fc["IGL"] == "on" ? true : false;
            bool supporter = fc["Supporter"] == "on" ? true : false;
            bool frag = fc["Fragger"] == "on" ? true : false;
            bool top = fc["Top"] == "on" ? true : false; //LOL ROLES
            bool mid = fc["Mid"] == "on" ? true : false;
            bool jung = fc["Jungle"] == "on" ? true : false;
            bool adc = fc["Adc"] == "on" ? true : false;
            bool sup = fc["Support"] == "on" ? true : false;
            string gameIDcs = fc["gameConnectIDcs"];
            string gameNickcs = fc["gameNickNamecs"];
            string gameNicklol = fc["gameNickNamelol"];

            DateTime date = new DateTime();
            date = Convert.ToDateTime(date1);

            users usr = new users();
            userGames usrGameLol = new userGames();
            userGames usrGameCs = new userGames();
            userGames usrGameFort = new userGames();
            userGames usrGamePubg = new userGames();
            userGames usrGameRocket = new userGames();
            userGameDescs topData = new userGameDescs();
            userGameDescs midData = new userGameDescs();
            userGameDescs jungData = new userGameDescs();
            userGameDescs adcData = new userGameDescs();
            userGameDescs supData = new userGameDescs();
            userGameDescs lolRankData = new userGameDescs();
            userGameDescs awpData = new userGameDescs();
            userGameDescs lurkerData = new userGameDescs();
            userGameDescs rifleData = new userGameDescs();
            userGameDescs iglData = new userGameDescs();
            userGameDescs supporterData = new userGameDescs();
            userGameDescs fragData = new userGameDescs();
            userGameDescs csRankData = new userGameDescs();
            userGameDescs usrGameDescCs = new userGameDescs();
            List<userGameDescs> userGameDescListLol = new List<userGameDescs>();
            List<userGameDescs> userGameDescListCs = new List<userGameDescs>();
            List<userGames> userGameList = new List<userGames>();
            if (lol)
            {
                usrGameLol.game = db.game.Find(1);
                usrGameLol.time = lolHours;
                usrGameLol.gameNickName = gameNicklol;
                lolRankData.compAtt = db.compAtt.Find(int.Parse(ranklol));
                userGameDescListLol.Add(lolRankData);
                if (top)
                {
                    topData.compAtt = db.compAtt.Find(82);
                    userGameDescListLol.Add(topData);
                }
                if (jung)
                {
                    jungData.compAtt = db.compAtt.Find(84);
                    userGameDescListLol.Add(jungData);
                }
                if (mid)
                {
                    midData.compAtt = db.compAtt.Find(83);
                    //var a2 = midData;
                    userGameDescListLol.Add(midData);
                }
                if (adc)
                {
                    adcData.compAtt = db.compAtt.Find(85);

TMF/Views/users/Delete.cshtml
@model TMF.Models.Entity.users

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dateOfBirth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dateOfBirth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mic)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mic)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.headset)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.headset)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.online)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.online)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TMF/Views/users/Details.cshtml
@model TMF.Models.Entity.users
@using TMF.Models.Entity

@{
    ViewBag.Title = "Details";
}

<h2>Profile</h2>
<link href="~/Content/css/userDetails.css" rel="stylesheet" />

<div class="content py-5  bg-light">
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <ul class="nav nav-tabs" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" href="#home" data-toggle="tab">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#gamesTab" data-toggle="tab">Games</a>
                    </li>
                </ul>
                <!-- form user info -->
                <div class="card card-outline-secondary tab-content">

                    <div id="home" class="tab-pane active">
                        <div class="card-header">
                            <h3 class="mb-0">User Information</h3>
                        </div>
                        <div class="card-body">
                            <form class="form" role="form" autocomplete="off">
                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label form-control-label">Username</label>
                                    <div class="col-lg-9">
                                        <input class="form-control" type="text" value="@Model.username" disabled>
                                    </div>
                                </div>
                                @if (Model.id == int.Parse(Session["id"].ToString()))
                                {
                                    <div class="form-group row">
                                        <label class="col-lg-3 col-form-label form-control-label">Password</label>
                                        <div class="col-lg-9">
                                            <input class="form-control" type="text" value="@Model.password" disabled>
                                        </div>
                                    </div>
                                }

                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label form-control-label">Age</label>
                                    @{ int age = 0;
                                        age = DateTime.Now.Year - Model.dateOfBirth.Year;
                                        if (DateTime.Now.DayOfYear < Model.dateOfBirth.DayOfYear)
                                        {
                                            age = age - 1;
                                        }
                                    }
                                    <div class="col-lg-9">
                                        <input class="form-control" type="email" value="@age" disabled>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label form-control-label">Mic</label>
                                    <div class="col-lg-9">
                                        <label for="mic" class="btn btn-primary">
                                            <input type="checkbox" id="mic" name="mic" class="badgebox" @if (Model.mic) { <text> checked </text> } disabled>
                                            <span class="badge">
                                                &check;
                                            </span>
                                        </label>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label form-control-label">Headset</label>
                                    <div class="col-lg-9">
                                        <label for="mic" class="btn btn-primary">
                                            <input type="checkbox" id="headset" name="headset" class="badgebox" @if (Model.headset) { <text> checked </text> } disabled>
                                            <span class="badge">
                                                &check;
                                            </span>
                                        </label>
                                    </div>
                                </div>
                                @if (Model.id == int.Parse(Session["id"].ToString()))
                                {
                                    <div class="form-group row">
                                        <label class="col-lg-6 col-form-label form-control-label"></label>
                                        <div class="col-lg-6">
                                            <input type="button" class="btn btn-success" value="Go to Edit" onclick="getEdit(@Model.id)">
                                        </div>
                                    </div>
                                }

                            </form>
                        </div>
                    </div>

                    <div id="gamesTab" class="tab-pane fade">
                        <div class="card-header">
                            <h3 class="mb-0">Games</h3>
                        </div>
                        <div class="card-body">
                            <form id="tab" class="form" role="form" autocomplete="off">
                                @for (int i = 0; i < Model.userGame.ToList().Count(); i++)
                                {

                                    <div class="form-group row">
                                        <label class="col-lg-3 col-form-label form-control-label"><b>Game Name</b></label>
                                        <div class="col-lg-9">
                                            <input class="form-control" type="text" value="@Model.userGame[i].game.name" disabled>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col-lg-3 col-form-label form-control-label">Hours</label>
                                        <div class="col-lg-9">
                                            <input class="form-control" type="text" value="@Model.userGame[i].time" disabled>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label class="col-lg-3 col-form-label form-control-label">Game Nickname</label>
                                        <div class="col-lg-9">
                                            <input class="form-control" type="text" value="@Model.userGame[i].gameNickName" disabled>
                                        </div>
                                    </div>
                                    if (Model.userGame[i].gameConnectID != null)
                                    {
                                        <div class="form-group row">
                                            <label class="col-lg-3 col-form-label form-control-label">Steam ID</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="text" value="@Model.userGame[i].gameConnectID" disabled>
                                            </div>
                                        </div>
                                    }

                                    foreach (var itemDesc in Model.userGame[i].userGameDesc)
                                    {
                                        <div class="form-group row">
                                            <label class="col-lg-3 col-form-label form-control-label">@itemDesc.compAtt.gameComponent.name</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="email" value="@itemDesc.compAtt.value" disabled>
                                            </div>
                                        </div>
                                    }
                                }
                                @*@foreach (var item in Model.userGame)
                                    {

                                        <div class="form-group row">
                                            <label class="col-lg-3 col-form-label form-control-label"><b>Game Name</b></label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="text" value="@item.game.name" disabled>
                                            </div>
                                        </div>

                                        <div class="form-group row">
                                            <label class="col-lg-3 col-form-label form-control-label">Hours</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="text" value="@item.time" disabled>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label class="col-lg-3 col-form-label form-control-label">Game Nickname</label>
                                            <div class="col-lg-9">
                                                <input class="form-control" type="text" value="@item.gameNickName" disabled>
                                            </div>
                                        </div>
                                        if (item.gameConnectID != null)
                                        {
                                            <div class="form-group row">
                                                <label class="col-lg-3 col-form-label form-control-label">Steam ID</label>
                                                <div class="col-lg-9">
                                                    <input class="form-control" type="text" value="@item.gameConnectID" disabled>
                                                </div>
                                            </div>
                                        }

                                        foreach (var itemDesc in item.userGameDesc)
                                        {
                                            <div class="form-group row">
                                                <label class="col-lg-3 col-form-label form-control-label">@itemDesc.compAtt.gameComponent.name</label>
                                                <div class="col-lg-9">
                                                    <input class="form-control" type="email" value="@itemDesc.compAtt.value" disabled>
                                                </div>
                                            </div>
                                        }

                                    }*@
                                <div class="form-group row">
                                    <label class="col-lg-3 col-form-label form-control-label"></label>
                                    <div class="col-lg-9">
                                        <input type="reset" class="btn btn-secondary" value="Return Home">
                                        <button type="button" class="btn btn-primary" id="opener">For Steam Dataset info</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
                <!-- /form user info -->
            </div>
        </div>
    </div>



</div>

<div id="steamPopup" title="Steam Dataset">
    <h6><b>Game Count</b></h6>
    <ul id="steamGameCount"></ul>
    <h6><b>Game List</b></h6>
    <ul id="steamGameList"></ul>
</div>
@if (Model.userGame.Any(u=>u.game.id==2))
{
    <input type="hidden" id="steamID" value="@Model.userGame.Where(u=>u.game.id==2).FirstOrDefault().gameConnectID" />

}
else
{
    <input type="hidden" id="steamID" value="0" />

}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css" />


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/js/apiJs.js"></script>

@section scripts{
    <script>
        function getEdit(ids) {
            location.href = "/users/edit/" + ids;
        }
    </script>
}

TMF/Views/users/Login.cshtml
@using TMF.Models.Entity
@model users

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link href="~/Content/css/login.css" rel="stylesheet" />

    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="~/Scripts/js/loginJS.js"></script>
    <script>
        function goSignUp() {
            location.href = "/users/Create";
        }
    </script>
    
</head>
<body>
    <input type="hidden" name="registerPage" value="1" />
    <div>
        <div class="container">
            <div id="login-box">
                <div class="logo">
                    <img src="~/TMF Documents/tmf.PNG" class="img img-responsive img-circle center-block" />
                    <h1 class="logo-caption"><span class="tweak">L</span>ogin</h1>
                </div><!-- /.logo -->
                <div class="controls">

                    <form action="@Url.Action("Login","users")" method="post">
                        <div id="loginDiv">
                            <input type="text" name="usernameL" placeholder="Username" class="form-control" />
                            <input type="password" name="passL" placeholder="Password" class="form-control" />
                            <button type="submit" class="btn btn-default btn-block btn-custom" id="login-btn1">Login</button>
                            <button type="button" id="kayitBtn" class="btn btn-default btn-block btn-custom" onclick="goSignUp()">Kayıt Ol</button>
                            <button type="button" class="btn btn-default btn-block btn-custom " style="background-color:dodgerblue" onclick="location.href='@Url.Action("Index", "Find" )'">
                                Return Home
                            </button>
                        </div>
                        
                    </form>

                </div><!-- /.controls -->
            </div><!-- /#login-box -->
        </div><!-- /.container -->
        <div id="particles-js"></div>
    </div>

</body>
</html>